ARG VERSION
FROM rustembedded/cross:i686-unknown-linux-gnu-$VERSION

FROM ubuntu:20.04
COPY --from=0 linux-runner linux-runner
COPY --from=0 /qemu /qemu

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --assume-yes --no-install-recommends \
    autoconf \
    automake \
    binutils \
    ca-certificates \
    clang \
    cmake \
    curl \
    file \
    g++ \
    gcc \
    git \
    libc6-dev \
    libgmp-dev \
    libmpc-dev \
    libmpfr-dev \
    libssl-dev \
    libtool \
    libxml2-dev \
    m4 \
    make \
    patch \
    pkg-config \
    python \
    xz-utils \
    zlib1g-dev

RUN dpkg --add-architecture i386 && apt-get update

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --assume-yes --no-install-recommends \
  libssl-dev:i386 gcc-multilib

# ENV I686_UNKNOWN_LINUX_GNU_OPENSSL_DIR="/usr/include/x86_64-linux-gnu"

ENV CARGO_TARGET_I686_UNKNOWN_LINUX_GNU_RUNNER="/linux-runner i686"