ARG VERSION
FROM vinodotdev/cross:armv7-unknown-linux-gnueabihf-base

RUN DEBIAN_FRONTEND=noninteractive dpkg --add-architecture armhf && \
    apt-get update && \
    apt-get install --assume-yes libssl-dev:armhf

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --assume-yes --no-install-recommends \
    autoconf \
    automake \
    binutils \
    ca-certificates \
    clang \
    cmake \
    curl \
    file \
    g++ \
    gcc \
    git \
    libc6-dev \
    libgmp-dev \
    libmpc-dev \
    libmpfr-dev \
    libssl-dev \
    libtool \
    libxml2-dev \
    m4 \
    make \
    patch \
    pkg-config \
    python \
    xz-utils \
    zlib1g-dev

RUN apt-get install -y libc6

ENV PKG_CONFIG_PATH=/usr/lib/arm-linux-gnueabihf/pkgconfig