ARG VERSION
FROM aarch64-unknown-linux-gnu-base

RUN DEBIAN_FRONTEND=noninteractive dpkg --add-architecture arm64 && \
  apt-get update && \
  apt-get install --assume-yes libssl-dev:arm64

# RUN apt-get install -y python-minimal

RUN apt-get install --assume-yes libc6-arm64-cross libc6-dev
# RUN apt-get install -y wget
# RUN wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key| apt-key add -
# RUN apt-get update
# RUN apt-get install -y clang:arm64 libclang-dev:arm64 llvm-dev:arm64
ENV PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig

# ENV RUSTFLAGS='-Clink-arg=-lstdc++'
