FROM ubuntu:20.04

RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y \
  libssl1.1 \
  ca-certificates \
  curl \
  git \
  less \
  vim \
  zip \
  && rm -rf

ARG user=vino
ARG group=vino
ARG uid=1000
ARG gid=1000

RUN useradd ${user} -m --shell $(which bash)

RUN mkdir -p /home/circleci && chmod a+rwx /home/circleci

COPY --chown=${user}:${group} dev-common /home/${user}/dev-common

RUN ln -s /home/${user}/dev-common/bin/* /usr/local/bin

USER ${user}:${group}

COPY dev-env.sh /tmp
RUN /tmp/dev-env.sh

COPY --chown=${user}:${group} nvm /home/${user}/.nvm
COPY bin/* /usr/local/bin/

