FROM rust:1.56.0

ARG user=vino
ARG group=vino
ARG uid=1000
ARG gid=1000

ENV CROSS_DOCKER_IN_DOCKER=true
ENV RUSTC_WRAPPER=/home/vino/.cargo/bin/sccache

RUN useradd ${user} -m --shell $(which bash)

COPY --chown=${user}:${group} sccache ${RUSTC_WRAPPER}

COPY linux-base.sh /tmp
RUN /tmp/linux-base.sh

USER ${user}:${group}

COPY --chown=${user}:${group} nvm /home/${user}/.nvm

COPY vino-base.sh /tmp
RUN /tmp/vino-base.sh

